#!/bin/bash
#
#SBATCH -J "GSidx"
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=40G

# modules loaded in ~/.bashrc

NOW=$(date --utc +%y%m%d.%H%M%SZ)

# index saved under ~/.gedi/genomic/${name}.oml
GEDI=/home/eboileau/install/GRAND-SLAM_2.0.5f/gedi

${GEDI} -e IndexGenome -s GRCh38_85_plus_Spikes_Isabel_fmtd.fa -a GRCh38_85_plus_Spikes_Isabel.gtf -n GRCh38_85_wspikes -nokallisto -nobowtie -nostar -D


